version: "3.5"

volumes:
  wordpress-data:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/tyago-ri/data/wordpress

  database-data:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/tyago-ri/data/database

networks:
  inception:
    driver: bridge

services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - database-data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    restart: always
    environment:
      - DOMAIN_NAME
      - MYSQL_DATABASE
      - MYSQL_HOSTNAME
      - MYSQL_USER
      - MYSQL_PASSWORD
      - WORDPRESS_NAME
      - WORDPRESS_USER_EMAIL
      - WORDPRESS_ROOT_LOGIN
      - WORDPRESS_ROOT_EMAIL
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - inception

  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - inception

